### ISSUE TITLE
OS X: AttributeError: 'svmem' object has no attribute 'buffers'

### ISSUE THREAD

**Issue by chenkins** [iarai/NeurIPS2021-traffic4cast#1]
```
(t4c) $ python baselines/baselines_cli.py  
[2021-06-15 20:29:52,217][INFO][38382][baselines_cli.py:main:287] Start build dataset
[2021-06-15 20:29:52,217][INFO][38382][baselines_cli.py:main:294] Check if files need to be untarred...
[2021-06-15 20:29:52,252][INFO][38382][baselines_cli.py:main:305] Dataset has size 519360
[2021-06-15 20:29:52,252][INFO][38382][baselines_cli.py:main:309] Create train_model.
[2021-06-15 20:29:52,407][INFO][38382][baselines_cli.py:main:323] Going to run train_model.
Traceback (most recent call last):
  File "baselines/baselines_cli.py", line 361, in <module>
    main(sys.argv[1:])
  File "baselines/baselines_cli.py", line 324, in main
    logging.info(system_status())
  File "/Users/che/workspaces/neurips2021-traffic4cast/util/monitoring.py", line 49, in system_status
    s += tabulate([[str(mem.__getattribute__(a)) for a in virtual_memory_fields]], headers=virtual_memory_fields) + "\n"
  File "/Users/che/workspaces/neurips2021-traffic4cast/util/monitoring.py", line 49, in <listcomp>
    s += tabulate([[str(mem.__getattribute__(a)) for a in virtual_memory_fields]], headers=virtual_memory_fields) + "\n"
AttributeError: 'svmem' object has no attribute 'buffers'
```

**Comment by chenkins** [comment]
Done https://github.com/iarai/NeurIPS2021-traffic4cast/commit/4d7bfde6a59dc313abce68817f5eb89a432c55dc
